### PR TITLE
Fix in VM-memory calculation for CloudSigma

### PR DESCRIPTION
**Pull request by sseycek**
Hi Nicolas,

a small fix for the memory calculation...

Also one thing we could consider is change the way CPU requirements are calculated for CloudSigma. Currently the minCores property is passed to the CloudSigma API where GHz is expected. So what we could do is use minCores for real cores in the deployment model and multiply it with 2500 before passing it to jClouds. This would result in typical cores available there.

Cheers,
Stepan

### CODE REVIEW

**Comment by nicolasferry** [comment]
Hi Stepan,

Once again many thanks for the fix!
Ok for the cores, I will change it.

Cheers,
Nicolas

**Comment by nicolasferry** [comment]
I just did the change for the cores.

Cheers,
Nicolas

**Comment by sseycek** [comment]
Very good - actually for the Zurich location you can multiply with 2600
as they have refreshed their hardware platform with 2.6GHz Xeons and let
you configure cores up to 2.6GHz.

Bye,
Stepan

Am 2015-08-11 21:59, schrieb nicolasferry:

**Comment by nicolasferry** [comment]
Ok I updated it to 2600.

Cheers,
Nicolas

**Pull request merged**
